version: '3.7'
services:
 web-backend:
  image: web-backend:latest
  build: .
  command: python Backend/manage.py runserver 0.0.0.0:8000
  ports:
   - "8000:8000"
 web-frontend:
  image: web-frontend:latest
  build: .
  ports:
   - "80:80"
