# Generated by Django 4.1.2 on 2022-10-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='direction',
        ),
    ]
